pgql-lang/src/main/java/oracle/pgql/lang/SpoofaxAstToGraphQuery.java, pgql-spoofax/syntax/Expressions.sdf3
Translate a string into a temporal object given a format.
The to_time and to_timestamp can be used for both with and without a timezone value.
Example: ``SELECT to_date('1999 Feb 19', 'yyyy MMM dd') WHERE (x)``
This is equivalent to ``SELECT DATE '1999-02-19' WHERE (x)``
=> to_date, to_time and to_timestamp functions

graph-query-ir/src/main/java/oracle/pgql/lang/ir/GraphQuery.java, graph-query-ir/src/main/java/oracle/pgql/lang/ir/PgqlUtils.java, pgql-lang/src/test/java/oracle/pgql/lang/PrettyPrintingTests.java
When pretty printing a path pattern, the path name is repeated instead of the showing the right connection.
<pre>
PATH abc := () -[:a|b|c]-> (b) 
PATH abc_star := <b>() -/:abc*/-> ()</b>
PATH abc_star_star := <b>() -/:abc_star*/-> ()</b>
SELECT m.name 
WHERE (n) -/:abc_star_star+/-> (m)
</pre>
<pre>
PATH abc := () -[anonymous_2]-> (b) WHERE (((anonymous_2.label() = 'a') OR (anonymous_2.label() = 'b')) OR (anonymous_2.label() = 'c'))
PATH abc_star_star := <b>() -/:abc_star_star+/-> ()</b>
PATH abc_star := <b>() -/:abc_star*/-> ()</b>
SELECT m.name
WHERE
(n) -/:abc_star_star+/-> (m)
</pre>
<pre>
PATH abc := () -[anonymous_2]-> (b) WHERE (((anonymous_2.label() = 'a') OR (anonymous_2.label() = 'b')) OR (anonymous_2.label() = 'c'))
PATH abc_star_star := <b>() -/:abc_star*/-> ()</b>
PATH …
=> Pretty printing fix and tests

graph-query-ir/src/main/java/oracle/pgql/lang/ir/PgqlUtils.java
Inside sub-queries pattern variables are not read. This might make queries like: SELECT EXISTS (SELECT m.random MATCH (a) -> (m)) MATCH (a) to not work because vertex (a) inside sub-query is not detected by the getVariables function.
=> Fix way we read pattern variables

pgql-spoofax/trans/normalized-signatures.str, pgql-spoofax/trans/trans-for-nabl.str, pgql-tests/error-messages/subqueries.spt, pgql-tests/reference-resolution/subqueries.spt
Now we always first try to resolve reference within a query, before using outer queries to resolve the rest of the variables.
=> Avoid generation of correlated queries if it can be avoided

example/run.sh, install.sh, pgql-tests/spring-boot-app/run.sh
This helps users which depend on their configured $MAVEN_OPTS (e.g. proxy settings)
=> Make run.sh and install.sh use $MAVEN_OPTS

pgql-lang/src/test/java/oracle/pgql/lang/MetadataTest.java, pgql-spoofax/trans/check.str
(if graph metadata is available)
=> don't allow SELECT n.* to end up returning zero columns

graph-query-ir/src/main/java/oracle/pgql/lang/ddl/propertygraph/EdgeTable.java, pgql-lang/src/main/java/oracle/pgql/lang/Pgql.java, pgql-lang/src/main/java/oracle/pgql/lang/TranslateCreatePropertyGraph.java, pgql-lang/src/test/java/oracle/pgql/lang/BugFixTest.java, pgql-lang/src/test/java/oracle/pgql/lang/PrettyPrintingTest.java, pgql-spoofax/syntax/DDL.sdf3, pgql-spoofax/syntax/pgql-lang.sdf3, pgql-spoofax/trans/check.str, pgql-spoofax/trans/normalize-ddl.str, pgql-spoofax/trans/normalize.str, pgql-tests/error-messages/DDL.spt, pgql-tests/error-messages/variable-length-paths.spt, pgql-tests/syntax/grouping-and-aggregating.spt, pgql-tests/syntax/pattern-matching.spt
- add support for source&destination vertex keys
- duplicate properties in PROPERTIES now errors out
- fixes the order of the ON clause and ONE ROW PER clause (ON clause should've come first)
=> CREATE PROPERTY GRAPH and ONE ROW PER improvements

graph-query-ir/src/main/java/oracle/pgql/lang/ir/QueryExpression.java, pgql-lang/src/main/java/oracle/pgql/lang/SpoofaxAstToGraphQuery.java, pgql-lang/src/test/java/oracle/pgql/lang/BugFixTest.java, pgql-lang/src/test/java/oracle/pgql/lang/SyntaxErrorsTest.java
PREFIX (e.g. SELECT n.* PREFIX 'N_' ..) was not preserved in the query IR if the query was parsed without providing graph metadata.
=> PREFIX not preserved when parsing without metadata

pgql-lang/pom.xml
New dependency tree looks like this:
```
[INFO] oracle.pg:pgql-lang:jar:0.0.0-SNAPSHOT
[INFO] +- oracle.pg:graph-query-ir:jar:0.0.0-SNAPSHOT:compile
[INFO] +- org.metaborg:org.metaborg.spoofax.core.uber:jar:2.5.16:compile
[INFO] |  +- io.usethesource:capsule:jar:0.6.3:compile
[INFO] |  +- org.apache.commons:commons-configuration2:jar:2.7:compile
[INFO] |  +- org.apache.commons:commons-text:jar:1.8:compile
[INFO] |  +- com.virtlink.commons:commons-configuration2-jackson:jar:0.10.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.11.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.0:compile
[INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.11.0 …
```
=> remove unneeded third parties

pgql-lang/src/test/java/oracle/pgql/lang/StaticOptimizationsTest.java, pgql-spoofax/trans/normalize-after.str
Push down predicates into LATERAL subquery even if the predicates reference correlated vertices.
PGQL version 2.0.1.8
=> Optimization: push down more predicates into LATERAL

pgql-lang/src/main/java/oracle/pgql/lang/SpoofaxAstToGraphQuery.java, pgql-lang/src/test/java/oracle/pgql/lang/BugFixTest.java, pgql-spoofax/.classpath, pgql-spoofax/trans/analysis.str, pgql-spoofax/trans/check.str, pgql-spoofax/trans/name-analysis.str, pgql-spoofax/trans/normalize.str, pgql-tests/error-messages/DDL.spt
This is needed for applications like GraphViz that do not provide metadata but still require SELECT * to be translated correctly into an equivalent query that does not contain SELECT *
=> Translate SELECT * in combination with LATERAL ( SELECT n.* even if no metadata is provided

pgql-lang/src/test/java/oracle/pgql/lang/BugFixTest.java, pgql-spoofax/editor/Colorer.esv, pgql-spoofax/trans/normalize.str
These bugs were introduced in my other PR here: https://github.com/oracle/pgql-lang/pull/114/commits/350787c88f2fece8f7086151b58abd35a65ebf4f
I found out about them thanks to PGX regression testing.
=> Two fixes related to has_label(..) normalization

pgql-lang/src/main/java/oracle/pgql/lang/TranslateCreatePropertyGraph.java, pgql-lang/src/test/java/oracle/pgql/lang/BugFixTest.java
It was only keeping the first element in the except list instead of all elements.
=> Fix bug in ALL ELEMENT TABLES EXCEPT

pgql-lang/src/test/java/oracle/pgql/lang/BugFixTest.java, pgql-spoofax/trans/check.str, pgql-tests/error-messages/DDL.spt
also add/improve checks for: 
- duplicate base graphs
- duplicate element tables in base graphs
=> remove incorrect error message for vertex table reference in base graph

pgql-lang/src/test/java/oracle/pgql/lang/MetadataTest.java, pgql-spoofax/trans/name-analysis.str
These queries would previously give errors like:
```
select n.* from match (n:account) group by n
^^^^
Property does not exist for any of the labels
```
```
SELECT n.* from lateral ( SELECT n from match (n:account) )
^^^^
Property does not exist for any of the labels
```
=> Fix error when doing v.* or e.* for vertices/edges projected from GROUP BY or LATERAL

graph-query-ir/src/main/java/oracle/pgql/lang/ir/PgqlUtils.java, graph-query-ir/src/main/java/oracle/pgql/lang/util/ReplaceExpressions.java, pgql-lang/src/main/java/oracle/pgql/lang/Pgql.java, pgql-lang/src/test/java/oracle/pgql/lang/MetadataTest.java, pgql-lang/src/test/java/oracle/pgql/lang/PrettyPrintingTest.java, pgql-lang/src/test/java/oracle/pgql/lang/StaticOptimizationsTest.java, pgql-spoofax/trans/check.str, pgql-spoofax/trans/common.str, pgql-spoofax/trans/name-analysis.str, pgql-spoofax/trans/names.nab, pgql-spoofax/trans/normalize-after.str, pgql-spoofax/trans/normalize.str, pgql-spoofax/trans/normalized-signatures.str, pgql-spoofax/trans/type-analysis.str, pgql-tests/error-messages/graph_table.spt
pgql version 2.0.4.1
For example, queries like:
```
SELECT *
FROM GRAPH_TABLE ( LdbcGraph MATCH (n) COLUMNS (n.*) )
FETCH FIRST 10 ROWS ONLY
```
are now translated into:
```
SELECT n.*
FROM MATCH (n) ON LdbcGraph
FETCH FIRST 10 ROWS ONLY
```
=> Merge LATERAL and GRAPH_TABLE into outer query when possible

pgql-lang/src/main/java/oracle/pgql/lang/SpoofaxAstToGraphQuery.java, pgql-lang/src/test/java/oracle/pgql/lang/BugFixTest.java, pgql-lang/src/test/java/oracle/pgql/lang/MetadataTest.java, pgql-spoofax/syntax/Legacy.sdf3, pgql-spoofax/trans/common.str, pgql-spoofax/trans/name-analysis.str, pgql-spoofax/trans/normalize-after.str, pgql-spoofax/trans/normalize.str, pgql-tests/error-messages/legacy/pgql10/disabled-pgql10-features.spt, pgql-tests/error-messages/modify.spt
Decided to keep supporting PGQL 0.9 and PGQL 1.0 after all and only desupport these two features:
- get rid of vertex patterns that have no parentheses, which was a feature that was part of the PGQL 0.9 spec `WHERE n -> m, n.prop > m.prop`.
- give a nice error message when `--`, `<--` and `-->` is used in PGQL 0.9 or PGQL 1.0 just like we already do for PGQL 1.1+. This because we want to repurpose the `--` to introduce a single-line comment and to be able to implement that we need to remove it from all PGQL versions.
This PR is also fixing two unrelated bugs:
- fix regression: x.* in combination with ONE ROW PER VERTEX/STEP was broken (when variable `x` is one of the iterator variables)
- fix bug: LATERAL containing INSERT/UPDATE/DELETE would crash the parser and now it's giving a nicer …
=> Remove some deprecated syntax and fix two bugs

graph-query-ir/src/main/java/oracle/pgql/lang/ir/PgqlUtils.java, pgql-lang/src/test/java/oracle/pgql/lang/PrettyPrintingTest.java, pgql-spoofax/syntax/GraphPattern.sdf3, pgql-spoofax/syntax/pgql-lang.sdf3, pgql-spoofax/trans/normalize.str, pgql-spoofax/trans/normalized-signatures.str, pgql-tests/error-messages/graph_table.spt, pgql-tests/error-messages/variable-length-paths.spt
Fix is that the pretty printer now adds the right parentheses around such MATCH clauses: `MATCH ( ... WHERE ...)` instead of `MATCH ... WHERE ...`
Additionally, the missing WHERE clause within parentheses had to be added to the syntax, which was planned since the start but never implemented.
=> Fix pretty printer generating invalid queries when pushing down a WHERE clause into a MATCH that is followed by a LATERAL

graph-query-ir/src/main/java/oracle/pgql/lang/ir/ExpAsVar.java, graph-query-ir/src/main/java/oracle/pgql/lang/ir/QueryEdge.java, graph-query-ir/src/main/java/oracle/pgql/lang/ir/QueryVariable.java, graph-query-ir/src/main/java/oracle/pgql/lang/ir/QueryVertex.java, graph-query-ir/src/main/java/oracle/pgql/lang/ir/VertexPairConnection.java, pgql-lang/src/main/java/oracle/pgql/lang/SpoofaxAstToGraphQuery.java, pgql-lang/src/test/java/oracle/pgql/lang/UniqueNameGenerationTest.java
Two variables may have the same name. For example when they appear in different subqueries or different clauses.
This PR adds a getUniqueName() to each variable that allows for distinguishing the variables names from one another.
The unique name is based on the offset of the variable in the original query text (e.g. in case of `SELECT 123 AS var FROM ...`, variable `var` will have unique name `var_(14, 17)` since character `v` has (0-based) index 14 and the space after `r` has index 17.
=> Expose unique names for variables

pgql-lang/src/main/java/oracle/pgql/lang/SpoofaxAstToGraphQuery.java
=> Improved IR for ONE ROW PER STEP (v1, e, v2) such that source and destination of edge are set to v1 and v2 instead of null
